MilShop.WebUI/Controllers/DetailViewController.cs
using MilShop.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MilShop.WebUI.Controllers
{
    public class DetailViewController : Controller
    {
        IShopRepository rep;
        // GET: DetailView
        public DetailViewController(IShopRepository repository)
        {
            rep = repository;
        }
        public ActionResult DisplayingDetails(object commodity)
        {

            var model = ((IEnumerable<dynamic>)commodity).Select(x => new
            {
                ModelName = x.ModelName,
                Price = x.Price1.Price1,
                Color = x.Color1.Color1,
                Size = x.Size1.Size1
            });
            return View(model);
        }
    }
}

MilShop.WebUI/Controllers/NavController.cs
using MilShop.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MilShop.WebUI.Controllers
{
    public class NavController : Controller
    {
        IShopRepository rep;

        public NavController(IShopRepository repository)
        {
            rep = repository;
        }
        // GET: Nav
        public PartialViewResult Menu(string category)
        {
            IEnumerable<string> categories = rep.GetType().GetProperties()
                                                          .Select(x => x.Name)
                                                          .Where(x => x != "Colors" 
                                                                   && x != "Sizes" 
                                                                   && x != "Prices");

            ViewBag.SelectedCategory = category;

            return PartialView(categories);
        }
    }
}

MilShop.WebUI/Views/Shared/Categories.cshtml
@model object

<div class="well col-md-4">
    @{
        dynamic _object = Model;
        <h3>    Model - @_object.ModelName                          </h3>
        <h5>    Size -  @_object.Size1.Size1                        </h5>
        <h5>    Color - @_object.Color1.Color1                      </h5>
        <h4>    Price - @_object.Price1.Price1.ToString("# грн")    </h4>
    }

    @using (Html.BeginForm("DisplayingDetails", "DetailView"))
    {
        <div class="pull-right">
            @Html.Hidden("commodity", Model)
            <input type="submit" class="btn btn-success" value="Подробнее" />
        </div>
    }

    @*@using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.Hidden("commodityId", (int)_object.Id)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value=""/>
        </div>
    }*@
</div>

MilShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>